version: '3.8'

services:
  recommandstock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommandstock
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - recommand-network

networks:
  recommand-network:
    driver: bridge
